# AppVeyor is a CI service to build and run tests under Windows
# https://ci.appveyor.com/project/districtdatalabs/yellowbrick

environment:

    matrix:
        # Tests failing on 32 bit architectures
        # https://github.com/numpy/numpy/issues/4384
        # - PYTHON: "C:\\Python27"
        #   PYTHON_VERSION: "2.7.14"
        #   PYTHON_ARCH: "32"

        - PYTHON: "C:\\Python27-x64"
          PYTHON_VERSION: "2.7.14"
          PYTHON_ARCH: "64"

        # - PYTHON: "C:\\Python36"
        #   PYTHON_VERSION: "3.6.4"
        #   PYTHON_ARCH: "32"

        - PYTHON: "C:\\Python36-x64"
          PYTHON_VERSION: "3.6.4"
          PYTHON_ARCH: "64"

        # - PYTHON: "C:\\Miniconda3"
        #   PYTHON_VERSION: "3.6.4"
        #   MINICONDA_VERSION: "4.4.10"
        #   PYTHON_ARCH: "32"

        # Currently broken, see #744
        # - PYTHON: "C:\\Miniconda3-x64"
        #   PYTHON_VERSION: "3.6.4"
        #   MINICONDA_VERSION: "4.5.12"
        #   PYTHON_ARCH: "64"


# Cancel pending jobs after first job failure
matrix:
    fast_finish: true

install:
    - "SET PATH=%MINICONDA3%;%MINICONDA3%\\Scripts;%PATH%"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "python -m pip install -U pip"
    - "python -m pip install -U wheel"
    - "python -m pip install -U -r requirements.txt"
    - "python -m pip install -U -r tests/requirements.txt"
    - "python -m nltk.downloader popular"

# No requirement to build any C libraries
build: off

test_script:
    - "python setup.py test"

after_test:
    - "python setup.py bdist_wheel"

artifacts:
    - path: dist\*

cache:
    # Use the appveryor cache to avoid redownload of numpy and scipy wheels
    - '%APPDATA%\pip\Cache'

notifications:
    - provider: Email
      to:
        - bbengfort@districtdatalabs.com
        - rbilbro@districtdatalabs.com
        - nathan.danielsen@gmail.com
      on_build_success: false
      on_build_failure: false
      on_build_status_changed: true
